### ISSUE TITLE
Provider怎么通知刷新弹窗内的数据呢？

### ISSUE THREAD

**Issue by momtboy** [q876625596/kumi_popup_window#3]

**Comment by q876625596** [comment]
在弹窗里面需要刷新的数据widget前套一层Selector或Consumer就行，具体请参照providers文档

**Comment by momtboy** [comment]
> 在弹窗里面需要刷新的数据widget前套一层Selector或Consumer就行，具体请参照providers文档

可以显示数据，当弹窗已经处于显示的状态，想在动态更新弹窗里面的数据，发现并没有生效，Provider非全局的情况下

**Comment by momtboy** [comment]
> 可以显示数据，当弹窗已经处于显示的状态，想在动态更新弹窗里面的数据，发现并没有生效，Provider非全局的情况下
补充：
Provider实际已经更新，但是弹窗内容却未发现变化
