### ISSUE TITLE
动画控制器偶发为null 导致dissmiss失效

### ISSUE THREAD

**Issue by hy20160705** [q876625596/kumi_popup_window#4]
### 错误日志
```
(11175): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'reverse' was called on null.
E/flutter (11175): Receiver: null
E/flutter (11175): Tried calling: reverse()
E/flutter (11175): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (11175): #1      KumiPopupWindow.dismiss (package:kumi_popup_window/kumi_popup_window.dart:322:23)
E/flutter (11175): #2      _IndexPageState._clickPopMenu (package:machineflutter/ui/index.dart:124:18)
E/flutter (11175): #3      _IndexPageState._buildPopMenu.<anonymous closure> (package:machineflutter/ui/index.dart:118:24)
E/flutter (11175): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:19)
E/flutter (11175): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (11175): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (11175): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (11175): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (11175): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (11175): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (11175): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (11175): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (11175): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (11175): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (11175): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (11175): #16     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (11175): #17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (11175): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (11175): #19     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (11175): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (11175): 
```
### 伪代码
```
Widget build(BuildContext context) {
    _context = context;
    initPop();
   // 控件点击事件
     onRightIconClick: () {
                    _popupWindow.show(_context);
                  },
}

void initPop() {
    _popupWindow = createPopupWindow(_context,
        duration: Duration(milliseconds: 200),
        gravity: KumiPopupGravity.rightTop,
        offsetX: ScreenUtil().setWidth(-10),
        offsetY: ScreenUtil().setWidth(-20),
        underStatusBar: false,
        underAppBar: true, childFun: (pop) {
      return GestureDetector(
          key: GlobalKey(),
          onTap: () {
            isSelect.value = !isSelect.value;
          },
          child: PopView(
              pathShape: PathShapeEnum.Top,
              radius: 10,
              percent: 0.8,
              child: Container(
                  width: ScreenUtil().setWidth(200),
                  height: ScreenUtil().setHeight(225),
                  padding: EdgeInsets.symmetric(
                      vertical: 0, horizontal: ScreenUtil().setWidth(18)),
                  color: Colours.color_white,
//                              decoration: ,
                  child: ListView(
                      padding: EdgeInsets.only(top: 10),
                      children: _buildPopMenus()))));
    });
  }

/// 构造单个PopMenu样式
  Widget _buildPopMenu(int index) {
    return Container(
        height: ScreenUtil().setHeight(70),
        child: ListTile(
          contentPadding: EdgeInsets.only(top: 0),
          title: Text(
            _popMenuList[index].label,
            style: TextStyle(
                color: Colours.color_525065,
                fontSize: ScreenUtil().setSp(22),
                fontWeight: FontWeight.w500),
          ),
          trailing: UI.icon(_popMenuList[index].iconPath,
              width: ScreenUtil().setWidth(28),
              height: ScreenUtil().setWidth(28)),
          onTap: () => _clickPopMenu(index),
        ));
  }

  /// popMenu点击事件
  _clickPopMenu(int index) {
    _popupWindow.dismiss(_context);
    switch (index) {
      case 0: // 切换仓库
        Fluttertoast.showToast(msg: '切换仓库');
        break;
      case 1: // 清除缓存
        Fluttertoast.showToast(msg: '清除缓存');
        break;
      case 2: // 退出登录
        Fluttertoast.showToast(msg: '退出登录');
        break;
    }
  }

  /// 构造popMenu列表
  List<Widget> _buildPopMenus() {
    return ListTile.divideTiles(
            context: context,
            tiles: _popMenuList
                .asMap()
                .keys
                .map((index) => _buildPopMenu(index))
                .toList())
        .toList();
  }

```

**Comment by q876625596** [comment]
你好，我这里测试了一下并没有发现该问题，对于AnimationController，我仅在PopupWindow执行dispose方法时将其同时dispose掉，会不会是你那边某些操作导致了PopupWindow被dispose掉了

**Comment by q876625596** [comment]
鉴于flutter页面刷新机制的问题，我同样不建议你使用一个变量将PopupWindow这种widget性质的东西保存起来复用，尽量保证在用到的时候重新create一个，这对性能的影响几乎可以忽略不计

**Comment by hy20160705** [comment]
那如果这样的话 没有持有这个实例 我要怎么让这个pop.dissmiss

**Comment by hy20160705** [comment]
哦 我明白你的意思了 你的意思是在childFun(pop)这里 利用传过来的pop去做操作是吧
```
childFun: (pop) {
    return Container(
      key: GlobalKey(),
      padding: EdgeInsets.all(10),
      height: 100,
      width: 100,
      color: Colors.redAccent,
    );
  },
```

**Comment by q876625596** [comment]
> 哦 我明白你的意思了 你的意思是在childFun(pop)这里 利用传过来的pop去做操作是吧
> 
> ```
> childFun: (pop) {
>     return Container(
>       key: GlobalKey(),
>       padding: EdgeInsets.all(10),
>       height: 100,
>       width: 100,
>       color: Colors.redAccent,
>     );
>   },
> ```

是的，我专门把pop传递出来的

**Comment by hy20160705** [comment]
好的 感谢

**Comment by hy20160705** [comment]
> > 哦 我明白你的意思了 你的意思是在childFun(pop)这里 利用传过来的pop去做操作是吧
> > ```
> > childFun: (pop) {
> >     return Container(
> >       key: GlobalKey(),
> >       padding: EdgeInsets.all(10),
> >       height: 100,
> >       width: 100,
> >       color: Colors.redAccent,
> >     );
> >   },
> > ```
> 
> 是的，我专门把pop传递出来的

还有一个问题
pop.dissmiss()会调用Navigator.pop(context);
假如我的popView中有个点击事件 点击的时候pop消失 同时有个dialog需要show出来 我的dialog会一闪而过 然后页面卡死 你能帮我看看是什么问题吗 没有报错信息
### 伪代码
```
_clickPopMenu(int index, KumiPopupWindow pop) {
    if (pop.isShow) {
      pop.dismiss(context);
    }
    switch (index) {
      case 0: // 切换仓库
        Fluttertoast.showToast(msg: '切换仓库');
        break;
      case 1: // 清除缓存
        Fluttertoast.showToast(msg: '清除缓存');
        break;
      case 2: // 退出登录
//        Fluttertoast.showToast(msg: '退出登录');
        Future.delayed(Duration(milliseconds: 100), () {
          MessageDialog.show(context,
              content: Strings.login_out_des, onConfirmListener: () {});
        });

        break;
    }
  }
```
### dialog
```
import 'package:flutter/material.dart';
import 'package:machineflutter/common/base_dialog.dart';
import 'package:machineflutter/res/colors.dart';
import 'package:machineflutter/res/strings.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

///
///   @Name    : merchant_machine
///   @author  : heyong
///   @date    : 2020/6/30 10:04 AM
///   @desc    : 消息弹窗
///   @version : 1.0
///

typedef OnConfirmListener = Function();
typedef OnCancelListener = Function();

class MessageDialog extends BaseDialog {
  final String content;
  final String cancel;
  final String confirm;
  final bool isShowCancel;
  final OnConfirmListener onConfirmListener;
  final OnCancelListener onCancelListener;

  MessageDialog(
      {Key key,
      this.content,
      this.cancel,
      this.confirm,
      this.isShowCancel,
      this.onConfirmListener,
      this.onCancelListener})
      : super(key: key);

  static MessageDialog show(
    BuildContext context, {
    @required String content,
    String confirm = Strings.sure,
    String cancel = Strings.cancel,
    bool isShowCancel = true,
    OnConfirmListener onConfirmListener,
    OnCancelListener onCancelListener,
  }) {
    MessageDialog dialog = MessageDialog(
      content: content,
      cancel: cancel,
      confirm: confirm,
      isShowCancel: isShowCancel,
      onConfirmListener: onConfirmListener,
      onCancelListener: onCancelListener,
    );
    return showBaseDialog(context, dialog);
  }

  @override
  Widget buildContent() {
    return MessageDialogWidget(
      content: content,
      cancel: cancel,
      confirm: confirm,
      isShowCancel: isShowCancel,
      onCancelListener: onCancelListener,
      onConfirmListener: onConfirmListener,
      dialog: this,
    );
  }
}

class MessageDialogWidget extends StatefulWidget {
  final String content;
  final String cancel;
  final String confirm;
  final bool isShowCancel;
  final OnConfirmListener onConfirmListener;
  final OnCancelListener onCancelListener;
  final BaseDialog dialog;

  MessageDialogWidget(
      {this.content,
      this.cancel,
      this.confirm,
      this.isShowCancel,
      this.onConfirmListener,
      this.onCancelListener,
      this.dialog});

  @override
  State<StatefulWidget> createState() => _MessageDialogWidgetState();
}

class _MessageDialogWidgetState extends State<MessageDialogWidget> {
  @override
  Widget build(BuildContext context) {
    return SizedBox(
        width: ScreenUtil().setWidth(440),
        height: ScreenUtil().setHeight(300),
        child: Card(
            color: Colors.white,
            elevation: 0.0,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.all(Radius.circular(10.0))),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Container(
                  width: double.infinity,
                  height: ScreenUtil().setHeight(170),
                  alignment: Alignment.center,
                  child: Text(
                    widget.content,
                    textAlign: TextAlign.center,
                    style: TextStyle(
                        color: Colours.color_333,
                        fontSize: ScreenUtil().setSp(28),
                        fontWeight: FontWeight.w500),
                  ),
                ),
                Offstage(
                  offstage: !widget.isShowCancel,
                  child: Divider(
                    height: ScreenUtil().setHeight(1),
                    color: Colours.color_DE,
                  ),
                ),
                Expanded(
                    child: Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  children: [
                    Expanded(
                        flex: widget.isShowCancel ? 1 : 0,
                        child: Offstage(
                          offstage: !widget.isShowCancel,
                          child: Container(
                            child: FlatButton(
                                onPressed: () {
                                  widget.dialog.dismiss();
                                  if (widget.onCancelListener != null) {
                                    widget.onCancelListener();
                                  }
                                },
                                child: Container(
                                  alignment: Alignment.center,
                                  child: Text(
                                    widget.cancel,
                                    style: TextStyle(
                                        color: Colours.color_333,
                                        fontSize: ScreenUtil().setSp(28)),
                                  ),
                                )),
                          ),
                        )),
                    Expanded(
                      flex: 1,
                      child: FlatButton(
                        shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                                bottomLeft: Radius.circular(
                                    widget.isShowCancel ? 0 : 10),
                                bottomRight: Radius.circular(10))),
                        color: Colours.color_FF714A,
                        onPressed: () {
                          widget.dialog.dismiss();
                          if (widget.onConfirmListener != null) {
                            widget.onConfirmListener();
                          }
                        },
                        child: Container(
                          width: double.infinity,
                          alignment: Alignment.center,
                          child: Text(
                            widget.confirm,
                            style: TextStyle(
                                color: Colours.color_white,
                                fontSize: ScreenUtil().setSp(34)),
                          ),
                        ),
                      ),
                    ),
                  ],
                ))
              ],
            )));
  }
}

```
### basedialog
```
import 'package:flutter/material.dart';

// ignore: must_be_immutable
abstract class BaseDialog extends Dialog {
  BuildContext context;
  Function onDismissListener;

  BaseDialog({Key key}) : super(key: key);

  void dismiss() {
    if (context != null) {
      Navigator.pop(context);
    }
    if (onDismissListener != null) {
      onDismissListener();
    }
  }

  @override
  Widget build(BuildContext context) {
    this.context = context;
    return GestureDetector(
      child: Material(
        type: MaterialType.transparency,
        child: Center(
          child: GestureDetector(
            child: buildContent(),
            onTap: () {
              ///拦截事件
            },
          ),
        ),
      ),
      onTap: () {
        if (touchOutsideDismiss) {
          dismiss();
        }
      },
    );
  }

  Widget buildContent();

  bool get cancelable => true;

  bool get touchOutsideDismiss => true;
}

typedef OnDismissListener = void Function();

/// 显示弹窗
T showBaseDialog<T extends BaseDialog>(BuildContext context, T dialog) {
  showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) => WillPopScope(
          child: dialog,
          onWillPop: () async {
            if (dialog.cancelable && dialog.onDismissListener != null) {
              dialog.onDismissListener();
            }
            return dialog.cancelable;
          }));
  return dialog;
}

```

**Comment by q876625596** [comment]
> > > 哦 我明白你的意思了 你的意思是在childFun(pop)这里 利用传过来的pop去做操作是吧
> > > ```
> > > childFun: (pop) {
> > >     return Container(
> > >       key: GlobalKey(),
> > >       padding: EdgeInsets.all(10),
> > >       height: 100,
> > >       width: 100,
> > >       color: Colors.redAccent,
> > >     );
> > >   },
> > > ```
> > 
> > 
> > 是的，我专门把pop传递出来的
> 
> 还有一个问题
> pop.dissmiss()会调用Navigator.pop(context);
> 假如我的popView中有个点击事件 点击的时候pop消失 同时有个dialog需要show出来 我的dialog会一闪而过 然后页面卡死 你能帮我看看是什么问题吗 没有报错信息
> 
> ### 伪代码
> ```
> _clickPopMenu(int index, KumiPopupWindow pop) {
>     if (pop.isShow) {
>       pop.dismiss(context);
>     }
>     switch (index) {
>       case 0: // 切换仓库
>         Fluttertoast.showToast(msg: '切换仓库');
>         break;
>       case 1: // 清除缓存
>         Fluttertoast.showToast(msg: '清除缓存');
>         break;
>       case 2: // 退出登录
> //        Fluttertoast.showToast(msg: '退出登录');
>         Future.delayed(Duration(milliseconds: 100), () {
>           MessageDialog.show(context,
>               content: Strings.login_out_des, onConfirmListener: () {});
>         });
> 
>         break;
>     }
>   }
> ```
> 
> ### dialog
> ```
> import 'package:flutter/material.dart';
> import 'package:machineflutter/common/base_dialog.dart';
> import 'package:machineflutter/res/colors.dart';
> import 'package:machineflutter/res/strings.dart';
> import 'package:flutter_screenutil/flutter_screenutil.dart';
> 
> ///
> ///   @Name    : merchant_machine
> ///   @author  : heyong
> ///   @date    : 2020/6/30 10:04 AM
> ///   @desc    : 消息弹窗
> ///   @version : 1.0
> ///
> 
> typedef OnConfirmListener = Function();
> typedef OnCancelListener = Function();
> 
> class MessageDialog extends BaseDialog {
>   final String content;
>   final String cancel;
>   final String confirm;
>   final bool isShowCancel;
>   final OnConfirmListener onConfirmListener;
>   final OnCancelListener onCancelListener;
> 
>   MessageDialog(
>       {Key key,
>       this.content,
>       this.cancel,
>       this.confirm,
>       this.isShowCancel,
>       this.onConfirmListener,
>       this.onCancelListener})
>       : super(key: key);
> 
>   static MessageDialog show(
>     BuildContext context, {
>     @required String content,
>     String confirm = Strings.sure,
>     String cancel = Strings.cancel,
>     bool isShowCancel = true,
>     OnConfirmListener onConfirmListener,
>     OnCancelListener onCancelListener,
>   }) {
>     MessageDialog dialog = MessageDialog(
>       content: content,
>       cancel: cancel,
>       confirm: confirm,
>       isShowCancel: isShowCancel,
>       onConfirmListener: onConfirmListener,
>       onCancelListener: onCancelListener,
>     );
>     return showBaseDialog(context, dialog);
>   }
> 
>   @override
>   Widget buildContent() {
>     return MessageDialogWidget(
>       content: content,
>       cancel: cancel,
>       confirm: confirm,
>       isShowCancel: isShowCancel,
>       onCancelListener: onCancelListener,
>       onConfirmListener: onConfirmListener,
>       dialog: this,
>     );
>   }
> }
> 
> class MessageDialogWidget extends StatefulWidget {
>   final String content;
>   final String cancel;
>   final String confirm;
>   final bool isShowCancel;
>   final OnConfirmListener onConfirmListener;
>   final OnCancelListener onCancelListener;
>   final BaseDialog dialog;
> 
>   MessageDialogWidget(
>       {this.content,
>       this.cancel,
>       this.confirm,
>       this.isShowCancel,
>       this.onConfirmListener,
>       this.onCancelListener,
>       this.dialog});
> 
>   @override
>   State<StatefulWidget> createState() => _MessageDialogWidgetState();
> }
> 
> class _MessageDialogWidgetState extends State<MessageDialogWidget> {
>   @override
>   Widget build(BuildContext context) {
>     return SizedBox(
>         width: ScreenUtil().setWidth(440),
>         height: ScreenUtil().setHeight(300),
>         child: Card(
>             color: Colors.white,
>             elevation: 0.0,
>             shape: RoundedRectangleBorder(
>                 borderRadius: BorderRadius.all(Radius.circular(10.0))),
>             child: Column(
>               mainAxisSize: MainAxisSize.min,
>               children: [
>                 Container(
>                   width: double.infinity,
>                   height: ScreenUtil().setHeight(170),
>                   alignment: Alignment.center,
>                   child: Text(
>                     widget.content,
>                     textAlign: TextAlign.center,
>                     style: TextStyle(
>                         color: Colours.color_333,
>                         fontSize: ScreenUtil().setSp(28),
>                         fontWeight: FontWeight.w500),
>                   ),
>                 ),
>                 Offstage(
>                   offstage: !widget.isShowCancel,
>                   child: Divider(
>                     height: ScreenUtil().setHeight(1),
>                     color: Colours.color_DE,
>                   ),
>                 ),
>                 Expanded(
>                     child: Row(
>                   mainAxisAlignment: MainAxisAlignment.start,
>                   children: [
>                     Expanded(
>                         flex: widget.isShowCancel ? 1 : 0,
>                         child: Offstage(
>                           offstage: !widget.isShowCancel,
>                           child: Container(
>                             child: FlatButton(
>                                 onPressed: () {
>                                   widget.dialog.dismiss();
>                                   if (widget.onCancelListener != null) {
>                                     widget.onCancelListener();
>                                   }
>                                 },
>                                 child: Container(
>                                   alignment: Alignment.center,
>                                   child: Text(
>                                     widget.cancel,
>                                     style: TextStyle(
>                                         color: Colours.color_333,
>                                         fontSize: ScreenUtil().setSp(28)),
>                                   ),
>                                 )),
>                           ),
>                         )),
>                     Expanded(
>                       flex: 1,
>                       child: FlatButton(
>                         shape: RoundedRectangleBorder(
>                             borderRadius: BorderRadius.only(
>                                 bottomLeft: Radius.circular(
>                                     widget.isShowCancel ? 0 : 10),
>                                 bottomRight: Radius.circular(10))),
>                         color: Colours.color_FF714A,
>                         onPressed: () {
>                           widget.dialog.dismiss();
>                           if (widget.onConfirmListener != null) {
>                             widget.onConfirmListener();
>                           }
>                         },
>                         child: Container(
>                           width: double.infinity,
>                           alignment: Alignment.center,
>                           child: Text(
>                             widget.confirm,
>                             style: TextStyle(
>                                 color: Colours.color_white,
>                                 fontSize: ScreenUtil().setSp(34)),
>                           ),
>                         ),
>                       ),
>                     ),
>                   ],
>                 ))
>               ],
>             )));
>   }
> }
> ```
> 
> ### basedialog
> ```
> import 'package:flutter/material.dart';
> 
> // ignore: must_be_immutable
> abstract class BaseDialog extends Dialog {
>   BuildContext context;
>   Function onDismissListener;
> 
>   BaseDialog({Key key}) : super(key: key);
> 
>   void dismiss() {
>     if (context != null) {
>       Navigator.pop(context);
>     }
>     if (onDismissListener != null) {
>       onDismissListener();
>     }
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     this.context = context;
>     return GestureDetector(
>       child: Material(
>         type: MaterialType.transparency,
>         child: Center(
>           child: GestureDetector(
>             child: buildContent(),
>             onTap: () {
>               ///拦截事件
>             },
>           ),
>         ),
>       ),
>       onTap: () {
>         if (touchOutsideDismiss) {
>           dismiss();
>         }
>       },
>     );
>   }
> 
>   Widget buildContent();
> 
>   bool get cancelable => true;
> 
>   bool get touchOutsideDismiss => true;
> }
> 
> typedef OnDismissListener = void Function();
> 
> /// 显示弹窗
> T showBaseDialog<T extends BaseDialog>(BuildContext context, T dialog) {
>   showDialog(
>       context: context,
>       barrierDismissible: false,
>       builder: (BuildContext context) => WillPopScope(
>           child: dialog,
>           onWillPop: () async {
>             if (dialog.cancelable && dialog.onDismissListener != null) {
>               dialog.onDismissListener();
>             }
>             return dialog.cancelable;
>           }));
>   return dialog;
> }
> ```

抱歉回复晚了，最近有些忙，这个问题你只需要在调用dismiss的时候在前面加上await就行了，如果你想禁用掉dismiss的动画，dismiss方法里面也有参数可以禁用

**Comment by hy20160705** [comment]
好的 谢谢

**Comment by hy20160705** [comment]
你好 最近在pop上增加TextField
发现增加SingleChildScrollView 不能解决软键盘遮挡输入框的问题

**Comment by q876625596** [comment]
> 你好 最近在pop上增加TextField
> 发现增加SingleChildScrollView 不能解决软键盘遮挡输入框的问题
不好意思，最近因为回国隔离，以及办公室搬迁的问题，一直很忙，没来得及回复，因为SingleChildScrollView 我平时基本没有用到，可以的话能贴一下代码吗，最好是能直接跑起来的代码

**Comment by yuyuxingchen** [comment]
你好 感谢你在百忙之中能够回复我
问题点我已经找到了 但是没有找到好的解决办法
设置SingleChildScrollView之后 软键盘还是遮挡输入框的主要原因是在我的项目中 我的项目是一个全屏的FLutterApp
所以我在Android中的manifest文件中将FlutterActivity的them修改为全屏的属性导致flutter这边在软键盘弹出时 获取到的软键盘高度为0（MediaQuery.of(context).viewInsets.bottom=0）导致了输入框被遮盖
```
 <activity
            android:name=".ui.activity.ScaleFlutterActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:theme="@style/FullTheme"
            android:windowSoftInputMode="adjustResize" >
<!--            <meta-data-->
<!--                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"-->
<!--                android:value="true" />-->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/FullTheme" />

            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

<style name="FullTheme" parent="Theme.AppCompat.NoActionBar">
        <item name="android:windowNoTitle">true</item>//无标题
        <item name="android:windowActionBar">false</item>//无ActionBar
        <item name="android:windowFullscreen">true</item>//全屏即无通知栏
        <item name="android:windowContentOverlay">@null</item>//是否有遮盖
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
```
我曾去flutter的GitHub中也没找到好的解决方案
最后找了一个折中的办法 监听了输入框弹起的时候 将输入框顶层的控件隐藏掉 实现输入框上移的功能

**Comment by yuyuxingchen** [comment]
> 你好 感谢你在百忙之中能够回复我
> 问题点我已经找到了 但是没有找到好的解决办法
> 设置SingleChildScrollView之后 软键盘还是遮挡输入框的主要原因是在我的项目中 我的项目是一个全屏的FLutterApp
> 所以我在Android中的manifest文件中将FlutterActivity的them修改为全屏的属性导致flutter这边在软键盘弹出时 获取到的软键盘高度为0（MediaQuery.of(context).viewInsets.bottom=0）导致了输入框被遮盖
> 
> ```
>  <activity
>             android:name=".ui.activity.ScaleFlutterActivity"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:theme="@style/FullTheme"
>             android:windowSoftInputMode="adjustResize" >
> 
> 
> 
>             <meta-data
>                 android:name="io.flutter.embedding.android.NormalTheme"
>                 android:resource="@style/FullTheme" />
> 
>             <meta-data
>                 android:name="io.flutter.embedding.android.SplashScreenDrawable"
>                 android:resource="@drawable/launch_background" />
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>         </activity>
> 
> <style name="FullTheme" parent="Theme.AppCompat.NoActionBar">
>         <item name="android:windowNoTitle">true</item>//无标题
>         <item name="android:windowActionBar">false</item>//无ActionBar
>         <item name="android:windowFullscreen">true</item>//全屏即无通知栏
>         <item name="android:windowContentOverlay">@null</item>//是否有遮盖
>         <item name="android:windowBackground">@drawable/launch_background</item>
>     </style>
> ```
> 
> 我曾去flutter的GitHub中也没找到好的解决方案
> 最后找了一个折中的办法 监听了输入框弹起的时候 将输入框顶层的控件隐藏掉 实现输入框上移的功能

登错账号了 还是本人

**Comment by q876625596** [comment]
> 你好 感谢你在百忙之中能够回复我
> 问题点我已经找到了 但是没有找到好的解决办法
> 设置SingleChildScrollView之后 软键盘还是遮挡输入框的主要原因是在我的项目中 我的项目是一个全屏的FLutterApp
> 所以我在Android中的manifest文件中将FlutterActivity的them修改为全屏的属性导致flutter这边在软键盘弹出时 获取到的软键盘高度为0（MediaQuery.of(context).viewInsets.bottom=0）导致了输入框被遮盖
> 
> ```
>  <activity
>             android:name=".ui.activity.ScaleFlutterActivity"
>             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
>             android:hardwareAccelerated="true"
>             android:theme="@style/FullTheme"
>             android:windowSoftInputMode="adjustResize" >
> 
> 
> 
>             <meta-data
>                 android:name="io.flutter.embedding.android.NormalTheme"
>                 android:resource="@style/FullTheme" />
> 
>             <meta-data
>                 android:name="io.flutter.embedding.android.SplashScreenDrawable"
>                 android:resource="@drawable/launch_background" />
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>         </activity>
> 
> <style name="FullTheme" parent="Theme.AppCompat.NoActionBar">
>         <item name="android:windowNoTitle">true</item>//无标题
>         <item name="android:windowActionBar">false</item>//无ActionBar
>         <item name="android:windowFullscreen">true</item>//全屏即无通知栏
>         <item name="android:windowContentOverlay">@null</item>//是否有遮盖
>         <item name="android:windowBackground">@drawable/launch_background</item>
>     </style>
> ```
> 
> 我曾去flutter的GitHub中也没找到好的解决方案
> 最后找了一个折中的办法 监听了输入框弹起的时候 将输入框顶层的控件隐藏掉 实现输入框上移的功能

我尝试了一下全屏模式，也发现了这个问题，而且我直接在listView中放了一个输入框，点击弹出键盘也依旧会遮挡，我感觉这个不是popup的问题，应该是flutter底层的问题

**Comment by q876625596** [comment]
> > 你好 感谢你在百忙之中能够回复我
> > 问题点我已经找到了 但是没有找到好的解决办法
> > 设置SingleChildScrollView之后 软键盘还是遮挡输入框的主要原因是在我的项目中 我的项目是一个全屏的FLutterApp
> > 所以我在Android中的manifest文件中将FlutterActivity的them修改为全屏的属性导致flutter这边在软键盘弹出时 获取到的软键盘高度为0（MediaQuery.of(context).viewInsets.bottom=0）导致了输入框被遮盖
> > ```
> >  <activity
> >             android:name=".ui.activity.ScaleFlutterActivity"
> >             android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
> >             android:hardwareAccelerated="true"
> >             android:theme="@style/FullTheme"
> >             android:windowSoftInputMode="adjustResize" >
> > 
> > 
> > 
> >             <meta-data
> >                 android:name="io.flutter.embedding.android.NormalTheme"
> >                 android:resource="@style/FullTheme" />
> > 
> >             <meta-data
> >                 android:name="io.flutter.embedding.android.SplashScreenDrawable"
> >                 android:resource="@drawable/launch_background" />
> >             <intent-filter>
> >                 <action android:name="android.intent.action.MAIN" />
> >                 <category android:name="android.intent.category.LAUNCHER" />
> >             </intent-filter>
> >         </activity>
> > 
> > <style name="FullTheme" parent="Theme.AppCompat.NoActionBar">
> >         <item name="android:windowNoTitle">true</item>//无标题
> >         <item name="android:windowActionBar">false</item>//无ActionBar
> >         <item name="android:windowFullscreen">true</item>//全屏即无通知栏
> >         <item name="android:windowContentOverlay">@null</item>//是否有遮盖
> >         <item name="android:windowBackground">@drawable/launch_background</item>
> >     </style>
> > ```
> > 
> > 
> > 我曾去flutter的GitHub中也没找到好的解决方案
> > 最后找了一个折中的办法 监听了输入框弹起的时候 将输入框顶层的控件隐藏掉 实现输入框上移的功能
> 
> 我尝试了一下全屏模式，也发现了这个问题，而且我直接在listView中放了一个输入框，点击弹出键盘也依旧会遮挡，我感觉这个不是popup的问题，应该是flutter底层的问题

虽然不知道你为什么要用全屏模式，但是即使不设置安卓端style的全屏，flutter也几乎能模拟全屏的效果

**Comment by yuyuxingchen** [comment]
> 虽然不知道你为什么要用全屏模式，但是即使不设置安卓端style的全屏，flutter也几乎能模拟全屏的效果

嗯嗯 全屏模式是因为业务需要
我这边尝试用flutter去设置全屏 看看是否能够监听到软键盘的高度去解决这个问题 
如果不能解决 只能用我那种曲线救国的方式了
再次感谢！

**Comment by q876625596** [comment]
> > 虽然不知道你为什么要用全屏模式，但是即使不设置安卓端style的全屏，flutter也几乎能模拟全屏的效果
> 
> 嗯嗯 全屏模式是因为业务需要
> 我这边尝试用flutter去设置全屏 看看是否能够监听到软键盘的高度去解决这个问题
> 如果不能解决 只能用我那种曲线救国的方式了
> 再次感谢！

还是非常抱歉这边没能解决你的这个问题。

**Comment by jasoncfpl** [comment]
> > 哦 我明白你的意思了 你的意思是在childFun(pop)这里 利用传过来的pop去做操作是吧
> > ```
> > childFun: (pop) {
> >     return Container(
> >       key: GlobalKey(),
> >       padding: EdgeInsets.all(10),
> >       height: 100,
> >       width: 100,
> >       color: Colors.redAccent,
> >     );
> >   },
> > ```
> 
> 是的，我专门把pop传递出来的


你好，我没太理解这段对话的意思，我看 childFunc 传递过来的 pop 也是一个 widget 啊
