### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by momtboy** [q876625596/kumi_popup_window#6]
空安全支持！！！

**Comment by q876625596** [comment]
> 空安全支持！！！

最近会更新flutter2版本api，以及dart的空安全支持

**Comment by momtboy** [comment]
> > 空安全支持！！！
> 
> 最近会更新flutter2版本api，以及dart的空安全支持

什么时候发布呢？？

**Comment by q876625596** [comment]
> > > 空安全支持！！！
> > 
> > 
> > 最近会更新flutter2版本api，以及dart的空安全支持
> 
> 什么时候发布呢？？

预计周五前

**Comment by q876625596** [comment]
> > > 空安全支持！！！
> > 
> > 
> > 最近会更新flutter2版本api，以及dart的空安全支持
> 
> 什么时候发布呢？？

已发布

**Comment by momtboy** [comment]
> > > > 空安全支持！！！
> > > 
> > > 
> > > 最近会更新flutter2版本api，以及dart的空安全支持
> > 
> > 
> > 什么时候发布呢？？
> 
> 已发布

好的，感谢
