### ISSUE TITLE
The setState() method does not update the UI

### ISSUE THREAD

**Issue by dany2709** [q876625596/kumi_popup_window#7]
I have a StatefulWidget, when showing show showPopupWindow() and making any changes within it, the changes are not activated, the popupWindow must be closed and reopened to see the changes

```
 IconButton(
        icon: Icon(MaterialIcons.remove),
        onPressed: () {
                   setState(() {
                         quantity = quantity - 1;
                  });
}),
Text(quantity.toString()),
```

**Comment by q876625596** [comment]
> I have a StatefulWidget, when showing show showPopupWindow() and making any changes within it, the changes are not activated, the popupWindow must be closed and reopened to see the changes
> 
> ```
>  IconButton(
>         icon: Icon(MaterialIcons.remove),
>         onPressed: () {
>                    setState(() {
>                          quantity = quantity - 1;
>                   });
> }),
> Text(quantity.toString()),
> ```

https://github.com/q876625596/kumi_popup_window/blob/0a9c7eac7103a389746356bd10824358476a2d75/example/lib/main.dart#L159 You need to nest StatefulBuilder and use the state provided in the builder
